In [1]:
import tensorflow as tf

In [2]:
row_dim, col_dim = 3, 3

In [3]:
zero_tsr = tf.zeros(shape=[row_dim, col_dim], dtype=tf.float32)

In [4]:
ones_tsr = tf.ones([row_dim, col_dim])

In [5]:
filled_tsr = tf.fill([row_dim, col_dim], 42)

In [6]:
constant_tsr = tf.constant([1, 2, 3])

In [7]:
zeros_similar = tf.zeros_like(constant_tsr)
ones_similar = tf.ones_like(constant_tsr)

In [8]:
linear_tsr = tf.linspace(start=0.0, stop=1.0, num=3)

In [9]:
linear_tsr

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0. , 0.5, 1. ], dtype=float32)>

In [10]:
integer_seq_tsr = tf.range(start=6, limit=15, delta=3)
integer_seq_tsr

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6,  9, 12], dtype=int32)>

In [11]:
randunif_tsr = tf.random.uniform([row_dim, col_dim], minval=0, maxval=1)
randunif_tsr

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.78308296, 0.23537588, 0.9923427 ],
       [0.5779834 , 0.8842201 , 0.78100276],
       [0.32250106, 0.73805845, 0.14699161]], dtype=float32)>

In [13]:
randnorm_tsr = tf.random.normal([row_dim, col_dim], mean=0.0, stddev=1.0)
randnorm_tsr

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.925636  ,  0.18255778, -0.7912087 ],
       [ 1.4206249 , -1.449163  ,  0.6263274 ],
       [-0.0823482 ,  0.6680618 ,  1.8149191 ]], dtype=float32)>

In [ ]:
# suffled_output = tf.random.shuffle(input_tensor)

In [15]:
height, width = (64, 64)

my_image = tf.random.uniform([height, width, 3], minval=0, maxval=155, dtype=tf.int32)

cropped_image = tf.image.random_crop(my_image, [height//2, width//2, 3])

print(my_image)
print(cropped_image)

tf.Tensor(
[[[ 70 125  23]
  [ 60 144  58]
  [ 78   1  23]
  ...
  [ 57 111  21]
  [ 22  76  17]
  [ 34 124  86]]

 [[152  55 132]
  [151  27 117]
  [148  46  87]
  ...
  [128  58  59]
  [104  77   0]
  [ 74  26  54]]

 [[103 133   2]
  [  4  24 122]
  [ 22  31 135]
  ...
  [ 11 134  80]
  [ 79  59 110]
  [152  94  27]]

 ...

 [[103  12 130]
  [ 44  62  93]
  [ 69  31  33]
  ...
  [125  63 144]
  [141  88 110]
  [149  51  33]]

 [[ 28 105  93]
  [ 23 122  30]
  [ 40 154  69]
  ...
  [ 96  88  85]
  [120   9 107]
  [ 97  96  96]]

 [[ 77 146 130]
  [114 149 126]
  [ 22 114 112]
  ...
  [ 95  42  14]
  [123  47 117]
  [ 42  85 142]]], shape=(64, 64, 3), dtype=int32)
tf.Tensor(
[[[144  58  78]
  [154  15 135]
  [132 141   0]
  ...
  [ 42  96  61]
  [ 51 120  72]
  [ 76  46  67]]

 [[140  98  95]
  [  4  74  57]
  [133 132 114]
  ...
  [  8 103 129]
  [  5 129 100]
  [ 58 145  92]]

 [[ 98  27 108]
  [153 125 129]
  [ 10  88 154]
  ...
  [102  13 104]
  [104 112   4]
  [ 23  64  75]]

 ..