In [1]:
import tensorflow as tf

In [2]:
identity_matrix = tf.linalg.diag([1.0, 1.0, 1.0])
identity_matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [3]:
A = tf.random.truncated_normal([2, 3])
A

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.40863764,  0.19051903,  0.34285125],
       [ 0.7647129 ,  1.0503919 , -0.40171397]], dtype=float32)>

In [4]:
B = tf.fill([2, 3], 5.0)
B

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)>

In [6]:
C = tf.random.uniform([3, 2])
C

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.9579334 , 0.8109447 ],
       [0.5634961 , 0.37079728],
       [0.20090747, 0.89082   ]], dtype=float32)>

In [9]:
import numpy as np

D = tf.convert_to_tensor(np.array([[1., 2., 3.],
                                  [-3., -7., -1.],
                                  [0., 5., -2.]]), dtype=tf.float32)
D

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.,  2.,  3.],
       [-3., -7., -1.],
       [ 0.,  5., -2.]], dtype=float32)>

In [10]:
print(A+B)

tf.Tensor(
[[4.5913625 5.190519  5.342851 ]
 [5.764713  6.050392  4.598286 ]], shape=(2, 3), dtype=float32)


In [11]:
print(B-B)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [13]:
print(tf.matmul(B, identity_matrix))

tf.Tensor(
[[5. 5. 5.]
 [5. 5. 5.]], shape=(2, 3), dtype=float32)


In [14]:
print(tf.multiply(D, identity_matrix))

tf.Tensor(
[[ 1.  0.  0.]
 [-0. -7. -0.]
 [ 0.  0. -2.]], shape=(3, 3), dtype=float32)


In [15]:
print(tf.transpose(C))

tf.Tensor(
[[0.9579334  0.5634961  0.20090747]
 [0.8109447  0.37079728 0.89082   ]], shape=(2, 3), dtype=float32)


In [16]:
print(tf.linalg.det(D))

tf.Tensor(-38.0, shape=(), dtype=float32)


In [17]:
print(tf.linalg.inv(D))

tf.Tensor(
[[-0.50000006 -0.5        -0.50000006]
 [ 0.15789475  0.05263158  0.21052633]
 [ 0.39473686  0.13157895  0.0263158 ]], shape=(3, 3), dtype=float32)


In [18]:
print(tf.linalg.cholesky(identity_matrix))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [19]:
print(tf.linalg.eigh(D))

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-10.659076  ,  -0.22750695,   2.886583  ], dtype=float32)>, <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.21749546, -0.6325011 , -0.74339646],
       [-0.84526515, -0.25879988,  0.46749276],
       [ 0.48808062, -0.7300446 ,  0.4783433 ]], dtype=float32)>)
